Arabic Documentation on Using Crowdin
Open-Science-Community-Saudi-Arabia/localisation pull request #15
Opened 2022-10-14 19:00 UTC by rnabage

2022-10-24 12:02 UTC, rnabage commented
Hello @BatoolMM I've submitted this PR, could you please review and let me know if I should make any corrections? Thank you.

2022-10-26 15:35 UTC, BatoolMM requested changes

2022-10-26 15:35 UTC, BatoolMM commented on docs/ruqayyah_docs.md
> +- عندما بدأت الترجمة شعرت بالحيرة فيما إذا كان ينبغي عليّ ترجمة حرفية لأن المتكلمين كانوا في بعض الأحيان غير مكتملين جملهم أو كرروا أنفسهم. مشكلة أخرى واجهتها هي أنّ بعض السلاسل المكتوبة للترجمة لم ت
The alignment here is LTR, not RTL!

2022-10-27 13:35 UTC, rnabage commented
Hello @BatoolMM I've effected the changes. Thank you!

2022-11-03 17:06 UTC, BatoolMM commented
This looks fantasic, thank you @rnabage!

2022-11-03 17:07 UTC, BatoolMM commented
@all-contributors please add @rnabage for documentation and translation

2022-11-03 17:07 UTC, merged