Create  required documentation
Open-Science-Community-Saudi-Arabia/localisation pull request #5
Opened 2022-04-14 15:27 UTC by nancyalaswad90

Include brief documentation in Arabic about the translation process of the project in Crowdin.

2022-04-14 15:28 UTC, nancyalaswad90 commented
Include brief documentation in Arabic about the translation process of the project in Crowdin.

2022-04-14 17:32 UTC, BatoolMM requested changes

2022-04-14 17:32 UTC, BatoolMM commented on docs/doc.md
> +> ## تجربتي مع موقع كرودن crowdin للترجمة  و التعريب
Crowdin is supposed to be written:
 (Crowdin) كراودن

2022-04-14 17:32 UTC, BatoolMM commented on docs/doc.md
> +ومن خلال برنامج العلوم المفتوحة لمجتمع السعودية [Open Science Community Saudi Arabia](https://form.jotform.com/220362171812446) اشتركت بموقع Crowdin، والذي يعتبر من أفضل المواقع للترجمة والتعريب التي
```suggestion
ومن خلال مجتمع العلوم المفتوحة في المملكة العربية السعودية [Open Science Community Saudi Arabia](https://osc-ksa.com/) شاركت في  منصة Crowdin، والذي يعتبر من أفضل المنصات للترجمة والتعريب التي تعاملت معها، كما عرفت ايضا انه موقع معتمد لدى كثير من الشركات منها ميكروسوفت و غوغل، حيث تقوم الشركات بوضع ملفات اللغة الخاصة بمواقعها او برامجها ومن ثم طلب تعريبها من الناس.
```

2022-04-14 17:32 UTC, BatoolMM commented on docs/doc.md
> +> - حيث نجد في هذه النافذة جميع الملفات الموجودةالتي يمكن ترجمتها.
```suggestion
> - حيث نجد في هذه النافذة جميع الملفات الموجودة التي يمكن ترجمتها. 
```

2022-04-14 17:32 UTC, BatoolMM commented on docs/doc.md
> +> - نختار احد المشاريع التي نهتم به ثم نقوم بترجمته ولكن ليس ترجمة حرفية، فنحن نقوم هنا بالتوطين بمعنى نعمل على  ترجمة المشروع بلغة عربية تتلاءم مع مفاهيم وثقافات البدلدان العربية بحيث يقدر كل باحث ق
```suggestion
> - نختار احد المشاريع التي نهتم به ثم نقوم بترجمته ولكن ليس ترجمة حرفية، فنحن نقوم هنا بالتوطين بمعنى نعمل على  ترجمة المشروع بلغة عربية تتلاءم مع مفاهيم وثقافات البلدان العربية بحيث يقدر كل باحث قام بالاطلاع على المشروع المقدم من قبلنا بفهم الافكار الموجودة فيه بسلاسة ووضوح.
```

2022-04-14 17:32 UTC, BatoolMM commented on docs/doc.md
> +> ### وللتوضيح اكثر ارجو الالطلاع على الرسوم المتحركة gif  ادناه، حيث نرى طريقة الترجمة لاسطر الملف ترجمة مفهومة ونرى ايضا وجود مشرفين يدعمون المترجمون في فهم اسلوب وخطوات العمل المطلوب.
```suggestion
> وللتوضيح اكثر ارجو الالطلاع على الرسوم المتحركة gif  ادناه، حيث نرى طريقة الترجمة لاسطر الملف ترجمة مفهومة ونرى ايضا وجود مشرفين يدعمون المترجمون في فهم اسلوب وخطوات العمل المطلوب.
```

2022-04-14 17:44 UTC, nancyalaswad90 reviewed
Thanks for your feedback

2022-04-14 17:44 UTC, nancyalaswad90 commented on docs/doc.md
> +> ## تجربتي مع موقع كرودن crowdin للترجمة  و التعريب
done

2022-04-14 17:47 UTC, BatoolMM commented on docs/doc.md
> +> ## تجربتي مع موقع كرودن crowdin للترجمة  و التعريب
Throughout all documents, it should be:
(Crowdin) كراودن

2022-04-14 17:53 UTC, nancyalaswad90 commented on docs/doc.md
> +> ## تجربتي مع موقع كرودن crowdin للترجمة  و التعريب
Please advice , should I make the changes here or in my repo   below , then add  other PR ?? 

https://github.com/nancyalaswad90/Outreachy/blob/main/document%20file%20.md

2022-04-14 18:00 UTC, nancyalaswad90 reviewed
I approve all the suggestion feedback , thanks @BatoolMM  for your support

2022-04-17 19:50 UTC, BatoolMM approved these changes

2022-04-17 19:50 UTC, BatoolMM commented on docs/doc.md
> + **ومن مميزات** برنامج العلوم المفتوحة لمجتمع السعودية ايضا التواصل مع مشرفين مثل الدكتورة batool@liverpool.ac.uk التي تقوم بتوجيهنا لاجراء خطوات الترجمة بشكل صحيح ومنظم، حتى يتنج عمل بمستوى متقدم.
```suggestion
 **ومن مميزات** برنامج العلوم المفتوحة لمجتمع السعودية ايضا التواصل مع مشرفين مثل [بتول المرزوق](https://batool-almarzouq.netlify.app/) التي تقوم بتوجيهنا لاجراء خطوات الترجمة بشكل صحيح ومنظم، حتى يتنج عمل بمستوى متقدم.
```

2022-04-17 19:51 UTC, BatoolMM commented
Thank you @nancyalaswad90 for this review!

2022-04-17 19:51 UTC, merged

2022-04-17 19:58 UTC, nancyalaswad90 commented
`**Thank you so much @BatoolMM   I appreciate your support all last days .**`