Create docs.md
Open-Science-Community-Saudi-Arabia/localisation pull request #6
Opened 2022-04-14 16:37 UTC by Boutainaelatbaoui

brief documentation in Arabic about the translation process of the project in Crowdin.

2022-04-14 16:46 UTC, Boutainaelatbaoui commented
Hello @BatoolMM, I just submitted a PR. Could you please give me your feedback?

2022-04-14 17:38 UTC, BatoolMM requested changes

2022-04-14 17:38 UTC, BatoolMM commented on docs/docs.md
> +# # توثيق عملية ترجمة المشروع في كراودن
```suggestion
## توثيق عملية ترجمة المشروع في كراودن
```

2022-04-14 17:38 UTC, BatoolMM commented on docs/docs.md
> +# # توثيق عملية ترجمة المشروع في كراودن
Crowdin is supposed to be written:
(Crowdin) كراودن

2022-04-14 17:38 UTC, BatoolMM commented on docs/docs.md
> +يعمل [مجتمع البيانات المفتوحة بالمملكة العربية السعودية](https://form.jotform.com/220362171812446) مع [منهج تورينج](https://the-turing-way.netlify.app/welcome.html) لتعريب مواردها التعليمية المفتوحة
```suggestion
يعمل [مجتمع البيانات المفتوحة بالمملكة العربية السعودية](https://form.jotform.com/220362171812446) مع [منهج تورينج](https://the-turing-way.netlify.app/welcome.html) لتعريب مواردها التعليمية المفتوحة وإتاحتها للمتعلمين المتحدثين باللغة العربية، وذلك عن طريق ترجمة وتدقيق فصول محددة منه باستخدام [كراودن](https://crowdin.com/).
```

2022-04-14 17:38 UTC, BatoolMM commented on docs/docs.md
> +يجب اختيار ملف واحد للعمل عليه من فصل `بحث قابل لإعادة الإنتاج`، ثم النقر على **الانتقال إلى المحرر**،
```suggestion

 يجب اختيار ملف واحد للعمل عليه من فصل `بحث قابل لإعادة الإنتاج`، ثم النقر على **الانتقال إلى المحرر**. 
- ```

2022-04-14 17:38 UTC, BatoolMM commented on docs/docs.md
> +المزيد من المعلومات حول كيفية استخدام محرر كراودن [هنا](https://support.crowdin.com/online-editor/)،
```suggestion
المزيد من المعلومات حول كيفية استخدام محرر كراودن [هنا](https://support.crowdin.com/online-editor/).
```

2022-04-14 17:38 UTC, BatoolMM commented on docs/docs.md
> +وقبل البدء في الترجمة يُفضَّل تصفح المحتوى عبر الملفات بدلاً من القائمة، وذلك من أجل فهم سياق النص وترجمته على أساس ذلك (كما توضّح الصورة أدناه يمكن تغيير طريقة العرض بالنقر على الرمز المحاط بالدائرة
```suggestion
وقبل البدء في الترجمة يُفضَّل تصفح المحتوى عبر الملفات بدلاً من القائمة، وذلك من أجل فهم سياق النص وترجمته على أساس ذلك (كما توضّح الصورة أدناه يمكن تغيير طريقة العرض بالنقر على الرمز المحاط بالدائرة).
```

2022-04-14 17:42 UTC, BatoolMM commented
Very comprehensive review - thank you for the PR. Can you fix the punctuation at the end of each **paragraph**, it should be a full stop, not a "comma". Also, can you write two sentences at the end summarising your own experience? did you find Crowdin easy or hard,  was the part you translated about "open data" interesting?

2022-04-14 19:44 UTC, Boutainaelatbaoui commented
I just updated the file and made all Changes requested. Thanks so much for your feedback @BatoolMM .

2022-04-17 19:46 UTC, BatoolMM approved these changes

2022-04-17 19:47 UTC, BatoolMM commented
@Boutainaelatbaoui - It looks awesome, I  like how you elaborated on the Crowdin Editor. Please don't forget to submit your final contribution through [this link](https://www.outreachy.org/outreachy-may-2022-internship-round/communities/open-science-community-saudi-arabia-oscsa/localisation-of-open-educational-resources-of-open/contributions/) include the steps you followed & what is the timeline to go through all the tasks - and what you anticipate to get out of this project. Please let me know if anything isn't clear!

2022-04-17 19:48 UTC, merged

2022-04-17 22:01 UTC, Boutainaelatbaoui commented
@BatoolMM Could you please help me? I'm unsure which link to put in my final contribution.
This link:
https://github.com/Open-Science-Community-Saudi-Arabia/localisation/blob/main/docs/docs.md
Or this:
https://github.com/Open-Science-Community-Saudi-Arabia/localisation/pull/6.
And thank you very much for your guidance and support.

2022-04-17 22:03 UTC, BatoolMM commented
You should add [this link](https://github.com/Open-Science-Community-Saudi-Arabia/localisation/pull/6) to your final contribution! Let me know if you have more questions!

2022-04-22 13:17 UTC, Boutainaelatbaoui commented
Hello @BatoolMM, I submitted the final application, and I want to make sure that I don't have to provide an additional community-specific questions.

2022-04-22 13:20 UTC, Boutainaelatbaoui commented
Hello @BatoolMM, I submitted the final application, and I want to make sure that I don't have to provide additional community-specific questions in the final application.

2022-04-22 14:10 UTC, BatoolMM commented
Yes, you don't have to - thank you @Boutainaelatbaoui for submitting your final application!

2022-04-22 14:40 UTC, Boutainaelatbaoui commented
Thank you so much @BatoolMM  for your answer, and I am so grateful for your help and support.